# /opt/shua/config.conf

# 下载链接 (默认为空)
DOWNLOAD_URL=""

# 每次下载完成后的休眠间隔时间 (单位：秒，默认 60 秒)
INTERVAL=60

# 允许工作的时间段。
# 格式为 HH:MM-HH:MM，多个时间段用英文逗号隔开。
# 例如：08:00-12:00,14:00-18:00
# 如果留空，则代表全天 24 小时运行。
TIME_WINDOWS=""
